# Install script for directory: C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/Demos

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/BULLET_PHYSICS")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/DX11ClothDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/HelloWorld/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/MultiThreadedDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/OpenCLClothDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/OpenGL/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/AllBulletDemos/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/CcdPhysicsDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/BulletXmlImportDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConstraintDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/SliderConstraintDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/GenericJointDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/Raytracer/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/RagdollDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ForkLiftDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/BasicDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/RollingFrictionDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/RaytestDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/VoronoiFractureDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/GyroscopicDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/FractureDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/Box2dDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/BspDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/MovingConcaveDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/VehicleDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/CharacterDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/SoftDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/SimplexDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/DynamicControlDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConvexHullDistance/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/DoublePrecisionDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConcaveDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/CollisionDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ContinuousConvexCollision/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/GjkConvexCastDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/MultiMaterialDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/SerializeDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/InternalEdgeDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/Benchmarks/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/ThreadingDemo/cmake_install.cmake")
  include("C:/Users/rqiu/Desktop/Physics/bullet-2.82-r2704/bullet-2.82-r2704/BulletBuild/Demos/VectorAdd_OpenCL/cmake_install.cmake")

endif()

